[Export]
baked_state = false
offer_binder = true
slider_server_url="https://pluto-dgp-hacvf.ondigitalocean.app/"
ignore_cache = [
    "index.jl",
]
create_index = false

[SliderServer]
exclude=[
    # these are in the repo but not used on the website
]
